# Generated by Django 4.2.2 on 2023-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_rename_baixa_movimentacaoestoque_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('baixa', 'Baixa')], default='entrada', max_length=10),
        ),
    ]
