# Generated by Django 4.2.2 on 2023-07-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_categoria'),
        ('estoque', '0004_remove_movimentacaoestoque_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
