# Generated by Django 4.2.2 on 2023-07-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_movimentacaoestoque_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='estoque',
        ),
    ]
