# Generated by Django 4.2.2 on 2023-07-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_categoria'),
        ('estoque', '0008_movimentacaoestoque_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='data',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='estoque',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
