# Generated by Django 4.2.2 on 2023-06-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('registro_de_compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='registro_de_compras.ItemCompra', to='produtos.produto'),
        ),
    ]
