# Generated by Django 4.2.2 on 2023-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0002_compra_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='preco',
            field=models.FloatField(),
        ),
    ]
