# Generated by Django 4.2.2 on 2023-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0003_alter_compra_preco_alter_itemcompra_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='preco',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
