# Generated by Django 4.2.2 on 2023-07-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_de_compras', '0004_alter_compra_preco_alter_itemcompra_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcompra',
            old_name='preco',
            new_name='preco_total',
        ),
    ]
